/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.alertproducer.avro;
@org.apache.avro.specific.AvroGenerated
public enum AlertColor implements org.apache.avro.generic.GenericEnumSymbol<AlertColor> {
  YELLOW, ORANGE, RED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertColor\",\"namespace\":\"com.example.alertproducer.avro\",\"symbols\":[\"YELLOW\",\"ORANGE\",\"RED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
